# Generated by Django 5.2.6 on 2025-09-11 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='deadline',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
